# Digital Ocean App Platform Configuration
name: dunet-fastmcp-server
region: nyc

services:
  - name: web
    github:
      repo: services-xrtechnology/dunet-fastmcp-server
      branch: main
      deploy_on_push: true

    # Comando para iniciar la app
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8070

    # Puerto HTTP
    http_port: 8070

    # Variables de entorno (configurables desde DO dashboard)
    envs:
      - key: ODOO_URL
        value: https://www.doonet.app
        scope: RUN_TIME
      - key: ODOO_DB
        value: doonet
        scope: RUN_TIME
      - key: ODOO_USERNAME
        value: admin
        scope: RUN_TIME
      - key: ODOO_PASSWORD
        scope: RUN_TIME
        type: SECRET

    # Recursos
    instance_count: 1
    instance_size_slug: basic-xxs

    # Health check
    health_check:
      http_path: /api/status
      initial_delay_seconds: 30
      period_seconds: 60
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 5
